# Paths
source:       ./_source
destination:  ./_site
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  
  work:
    output: true
    permalink: /work/:path/
plugins_dir:  null

# Debug
overlays: false

# Site settings
title: James Shakespeare
baseurl: "" # the subpath of your site, e.g. "/path" or "" (no trailing slash)
url: "" # the base hostname & protocol for your site without trailing slash

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"

# Build settings
markdown: kramdown

# Project Settings
exclude:
  - "README.md"
  - "node_modules"
  - "gulpfile.js"
  - "gulpfile.babel.js"
  - "package.json"
  - "*.sublime-*"
  - "Gemfile"
  - "Gemfile.lock"
  - "_assets"
  - "_tasks"
  - "_config"

keep_files:
  - "assets"
